name: mx_notifiers
description: Collection of should have StateNotifiers for combining with Riverpod/Provider
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/mx_notifiers/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  state_notifier: ">=0.7.2+1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_riverpod: ^2.0.0-dev.3
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main

flutter: