name: podex
description: Collection of should have StateNotifiers for combining with Riverpod/Provider
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/podex/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  riverpod: ">=2.0.0-dev.5 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  mockito: ^5.1.0
  fake_async: ^1.2.0
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main