name: podex
description: Collection of should have StateNotifiers for combining with Riverpod/Provider
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/podex/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  state_notifier: ">=0.7.2+1 <1.0.0"
  meta: 1.7.0

dev_dependencies:
  clock: ^1.1.1
  fake_async: ^1.3.1
  lints: ^2.0.0
  mockito: ^5.2.0
  riverpod: ">=2.0.0-dev.9 <3.0.0"
  test: ^1.20.0
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main
