name: podex
description: Collection of should have StateNotifiers for combining with Riverpod/Provider
version: 1.0.0
homepage: http://mehmetesen.com
repository: https://github.com/esenmx/podex/

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  state_notifier: ">=0.7.2+1 <1.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  mockito: ^5.1.0
  fake_async: ^1.2.0
  riverpod: ^2.0.0-dev.3
  test_utils:
    git:
      url: https://github.com/esenmx/test_utils
      ref: main